import { Box, Chip, Container, Stack, Typography } from '@mui/material'
import { curriculum, gradeDisplayName, gradeOptions } from '../data/curriculum'
import { ChordStaff } from '../components/ChordStaff'
import { toVexKeySignature } from '../music/noteUtils'
import type { ScaleExercise } from '../types/curriculum'

// Generated by scripts/render_rcm_audit.py; missing until that script has been run
const bookPages = import.meta.glob<string>('../../reference/audit/*.png', { eager: true, query: '?url', import: 'default' })

const pageImage = (page: number) => bookPages[`../../reference/audit/p${page}.png`]

function ScaleRow({ scale }: { scale: ScaleExercise }) {
    return (
        <Stack spacing={1} sx={{ py: 1.5, borderTop: 1, borderColor: 'divider' }}>
            <Typography sx={{ fontWeight: 700 }}>
                {scale.scaleName}
                {scale.minorForm ? ` (${scale.minorForm})` : ''}
            </Typography>
            <Stack direction="row" spacing={0.5} useFlexGap sx={{ flexWrap: 'wrap' }}>
                {scale.sequence.map((event) => (
                    <Chip
                        key={event.id}
                        size="small"
                        variant="outlined"
                        label={`${event.romanNumeral} ${event.symbol}: ${event.notes.join(' ')} · ${event.fingerings?.join('') ?? ''}`}
                    />
                ))}
            </Stack>
            <ChordStaff events={scale.sequence} keySignature={toVexKeySignature(scale.tonic, scale.mode)} />
        </Stack>
    )
}

export function AuditPage() {
    if (!curriculum) return <Typography>Curriculum failed validation.</Typography>

    return (
        <Container maxWidth="xl" sx={{ py: 3 }}>
            <Typography variant="h4" gutterBottom>
                RCM voicing audit
            </Typography>
            <Typography color="text.secondary" sx={{ mb: 3 }}>
                The level&apos;s book pages (left, scrollable) next to the app&apos;s data for every scale in that level (right).
                Notes are written pitch, low to high; fingerings follow the same order (0 = open string).
            </Typography>
            {gradeOptions.map((grade) => {
                const scales = curriculum!.grades[grade]
                const pages = [...new Set(scales.flatMap((s) => s.sourcePages))].sort((a, b) => a - b)
                return (
                    <Box key={grade} sx={{ mb: 5 }}>
                        <Typography variant="h5" sx={{ mb: 2 }}>
                            {gradeDisplayName(grade)}
                        </Typography>
                        <Stack direction={{ xs: 'column', md: 'row' }} spacing={3} sx={{ alignItems: 'flex-start' }}>
                            <Stack
                                spacing={1}
                                sx={{ flex: '0 0 440px', position: { md: 'sticky' }, top: 8, maxHeight: { md: '96vh' }, overflowY: 'auto' }}
                            >
                                {pages.map((page) =>
                                    pageImage(page) ? (
                                        <Box key={page} component="img" src={pageImage(page)} alt={`RCM page ${page}`} sx={{ width: '100%', border: 1, borderColor: 'divider' }} />
                                    ) : (
                                        <Typography key={page} color="error">
                                            Page {page}: run scripts/render_rcm_audit.py to render it.
                                        </Typography>
                                    ),
                                )}
                            </Stack>
                            <Box sx={{ flex: 1, minWidth: 0 }}>
                                {scales.map((scale) => (
                                    <ScaleRow key={scale.id} scale={scale} />
                                ))}
                            </Box>
                        </Stack>
                    </Box>
                )
            })}
        </Container>
    )
}
